name: Fed-BioMed End-to_End tests
run-name: Fed-BioMed End-to_End test
permissions: write-all
on:
  push: 
    branches:
      - 'feature/479-bug-in-integration-test'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - review_requested
      - ready_for_review

    branches:
      - feature/479-bug-in-integration-test


jobs:
  e2e-test:
    name: e2e tests
    strategy:
      fail-fast: false # Importance ?
      matrix:
        os: [ubuntu-22-04, fedora38] # \todo must be restored at the end of debugging: [ubuntu-22-04, fedora38, macosx-m1]
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: Checkout of head
        id: e2e-checkout
        uses: actions/checkout@v3

#      - name: setup datasets
#        id: e2e-setup-datasets
#        run: |
#          echo "Setting up the datasets"
#          echo $SHELL
#          source $HOME/.bashrc
#          ./notebooks/101_getting-started-setup.sh
#        shell: bash -l {0}

      - name: Run end-to-end tests
        id: e2e-tests
        run: |
          echo "Launching end-to-end tests" # to check from time to time
          ./scripts/run_end_to_end_tests.sh
          ls ./rep*
        shell: bash -l {0}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: (${{ matrix.os }}) Fedbiomed End-to-End Tests            # Name of the check run which will be created
          artifact: /\.\/end_tests_outputs\/(.*)/
          path: ./report.xml    # Path to test results
          reporter: java-junit        # Format of test results

