name: Fed-BioMed End-to_End tests
run-name: Fed-BioMed End-to_End test
on:
  push: 
    branches:
      - 'feature/479-bug-in-integration-test'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - review_requested
      - ready_for_review

    branches:
      - feature/479-bug-in-integration-test


jobs:
  e2e-test:
    name: e2e tests
    strategy:
      fail-fast: false # Importance ?
      matrix:
        os: [ubuntu-22-04] #[ubuntu-22-04, fedora38, macosx-m1]
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: Checkout of head
        id: e2e-checkout
        uses: actions/checkout@v3

      - name: setup datasets
        id: e2e-setup-datasets
        run: |
          echo "Setting up the datasets"
          ./notebooks/101_getting-started-setup.sh

      - name: Run end-to-end tests
        id: e2e-tests
        run: |
          echo "Launching end-to-end tests" # to check from time to time
          ./scripts/run_end_to_end_tests.sh
          echo "============== TAP results ====================="
          cat ./report.tap | grep -v "^#"
        shell: bash -l {0}

