name: Fed-BioMed End-to_End tests
run-name: Fed-BioMed End-to_End test
permissions: write-all
on:
  schedule:
    - cron: '30 1 * * *'

  workflow_dispatch:

  push:
    branches:
      - 'feature/479-bug-in-integration-test'
      - 'develop'
      - 'master'

jobs:
  e2e-test:
    name: e2e tests
    strategy:
      fail-fast: false # Importance ?
      matrix:
        os: [ubuntu-22-04, fedora38, macosx-m1]
    runs-on: ${{ matrix.os }}
      
    steps:
      - name: Checkout of head
        id: e2e-checkout
        uses: actions/checkout@v3

      - name: Run end-to-end tests
        id: e2e-tests
        run: |
          echo "Launching end-to-end tests" # to check from time to time
          ./scripts/run_end_to_end_all.sh
          ls ./rep*
          ls ./end_to_end_tests_outputs/*
        shell: bash -l {0}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # run this step even if previous step failed
        with:
          name: (${{ matrix.os }}) Fedbiomed End-to-End Tests            # Name of the check run which will be created
          path: ./report.xml    # Path to test results
          reporter: java-junit        # Format of test results

      - name: Upload Test Logs
        uses: actions/upload-artifact@v3  # upload test results
        if: always()      # run this step even if previous step failed
        with:
          name: test-results-${{ matrix.os }}
          path: ./end_to_end_tests_outputs/*.log

